<Project>
  <PropertyGroup>
    <AssemblyName>ExcelSupport</AssemblyName>
    <IntermediateOutputPath>obj\release\</IntermediateOutputPath>
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>C:\SourceCode\ExcelSupport\obj\</MSBuildProjectExtensionsPath>
    <_TargetAssemblyProjectName>ExcelSupport</_TargetAssemblyProjectName>
    <RootNamespace>ExcelSupport</RootNamespace>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ExcelDna.AddIn" Version="1.8.0" />
    <PackageReference Include="ExcelDna.Integration" Version="1.8.0" />
    <PackageReference Include="ExcelDna.Interop" Version="15.0.1" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Oracle.ManagedDataAccess" Version="19.18.0" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="USER_MANUAL.md" />
    <EmbeddedResource Include="Ribbon\CustomRibbon.xml" />
    <EmbeddedResource Include="Languages\*.json" />
  </ItemGroup>
  <ItemGroup>
    <ReferencePath Include="C:\Users\User\.nuget\packages\exceldna.integration\1.8.0\lib\net452\ExcelDna.Integration.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\Microsoft.CSharp.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\exceldna.interop\15.0.1\lib\net452\Microsoft.Office.Interop.Excel.dll">
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </ReferencePath>
    <ReferencePath Include="C:\Users\User\.nuget\packages\exceldna.interop\15.0.1\lib\net452\Microsoft.Vbe.Interop.dll">
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </ReferencePath>
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\mscorlib.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\newtonsoft.json\13.0.3\lib\net45\Newtonsoft.Json.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\exceldna.interop\15.0.1\lib\net452\Office.dll">
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </ReferencePath>
    <ReferencePath Include="C:\Users\User\.nuget\packages\oracle.manageddataaccess\19.18.0\lib\net40\Oracle.ManagedDataAccess.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\PresentationCore.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\PresentationFramework.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Core.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Data.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Drawing.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.IO.Compression.FileSystem.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Net.Http.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Numerics.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Runtime.Serialization.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Windows.Controls.Ribbon.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Windows.Forms.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Xaml.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Xml.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Xml.Linq.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\UIAutomationClient.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\UIAutomationClientsideProviders.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\UIAutomationProvider.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\UIAutomationTypes.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\WindowsBase.dll" />
    <ReferencePath Include="C:\Users\User\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\WindowsFormsIntegration.dll" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Ai\AiAssistantControl.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Ai\AiFormulaDoctorDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Ai\AiQuickTranslatePopup.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Ai\AiSettingsControl.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Ai\AiTranslateDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Ai\TranslationEditorDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Common\ExcelColorPicker.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Common\ProjectProfileSettingsControl.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Common\ProjectProfileSettingsDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Common\QuickActionBarWindow.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Common\QuickCommandPaletteDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Common\RibbonCustomizeDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Common\RulerHudWindow.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Common\SpecVersionSelectorDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Common\UserManualDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Data\AdvancedFilterDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Data\BatchCleanerAndMergeDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Data\BatchFileConverterDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Data\BatchFindReplaceDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Data\DataCleaningWizardDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Data\DuplicateFinderDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Data\ExternalLinksManagerDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Data\FilteredCopyPasteDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Data\FuzzyDuplicateDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Data\SpecialCopyDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Data\SqlScriptGeneratorDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Data\TableExportDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Data\VisualTableMergeDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Japanese\GlossaryDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Japanese\JapanesePresetManagerDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Japanese\JapaneseTextConverterDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Japanese\KatakanaValidatorDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Japanese\VietnameseCheckDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Oracle\OracleConnectionSettingsControl.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Oracle\OracleQuickQueryDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Oracle\OracleTableCompareDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Oracle\OracleTableStructureDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Workbook\DesignPageCounterDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Workbook\RenameSheetDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Workbook\SheetSnapshotDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Workbook\SheetToolsDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Workbook\WorkbookCompareDialog.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\Views\Workbook\WorkbookTreeViewControl.g.cs" />
    <Compile Include="C:\SourceCode\ExcelSupport\obj\release\net48\GeneratedInternalTypeHelper.g.cs" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>